### ISSUE TITLE
Langage frontend

### ISSUE THREAD

**Issue by ron190** [mtg-peasant/mtg-peasant-backend#2]
Au choix:
- React / Typescript
- PHP
- ...

Besoins: Tournoi, Article, PM, Forum, Search, Valideck

L'accès à des données backend par API permet d'avoir un frontend moins statique (cf. gmail, github, etc)

**Comment by Marcel-Brouette** [comment]
I'm a big fan of Vue.js which is similar to React and easy to learn : 
https://fr.vuejs.org/v2/guide/comparison.html#React
Both are similar but my choice would go to Vue.js particulary for the easiest syntax (subjective point)

**Comment by ron190** [comment]
J'ai regardé un peu de doc sur Vue.js, on peut aussi faire du Typescript, du JSX, du Vuex, ça paraît bien balaise.
